version: '3'
services:
	DEV-1:
		image: 'tomcat:9.0.68-jre8-temurin-jammy'
		ports:
		- "8090:8080"
		volumes:
		- "/mnt/jenkins-slave1:/usr/local/tomcat/webapps/"

	DEV-2:
		image: 'tomcat:9.0.68-jre8-temurin-jammy'
		ports:
		- "9090:8080"
		volumes:
		- "/mnt/jenkins-slave1:/usr/local/tomcat/webapps/"
